import { Driver, Ambulance, Patient, Hospital, TripHistoryItem, EarningsData } from '@/types';

export const INITIAL_DRIVER: Driver = {
  id: 'DRV-9021',
  name: 'Raj Kumar',
  phone: '+91 98765 43210',
  ambulanceNumber: 'DL 01 AB 1234',
  status: 'ONLINE',
  rating: 4.92,
  totalTrips: 824,
  currentLocation: {
    lat: 28.6189,
    lng: 77.3654, // Sector 62, Noida driver base
  },
  verificationStatus: 'VERIFIED',
  profileImage: '',
  licenseNumber: 'DL-0420190038291',
  experienceYears: 6,
};

export const INITIAL_AMBULANCE: Ambulance = {
  id: 'AMB-104',
  driverId: 'DRV-9021',
  registrationNumber: 'DL 01 AB 1234',
  type: 'ALS', // Advanced Life Support
  capacity: '1 Stretcher + 2 Attendants + Paramedic',
  equipment: [
    'Automated External Defibrillator (AED)',
    'Transport Ventilator (Hamilton-T1)',
    'Portable Medical Oxygen (2x 10L cylinders)',
    'Cardiac Monitor with 12-Lead ECG',
    'Emergency Trauma & Immobilization Kit',
    'Infusion Syringe Pump',
    'Suction Unit & Intubation Set',
  ],
  status: 'ACTIVE',
  oxygenLevel: 94,
  ventilatorAvailable: true,
  defibrillatorAvailable: true,
};

export const INITIAL_PATIENT: Patient = {
  id: 'PAT-4829',
  name: 'Rahul Sharma',
  age: 44,
  gender: 'Male',
  phone: '+91 98112 34567',
  emergencyLevel: 'HIGH',
  medicalCondition: 'Acute chest pain radiating to left arm, shortness of breath, suspected NSTEMI/cardiac emergency.',
  vitals: {
    heartRate: 112,
    spo2: 91,
    bp: '158/94 mmHg',
    temperature: '98.6°F',
  },
  specialRequirements: ['Cardiac ICU Bed Required', 'On-call Interventional Cardiologist', 'Immediate Cath Lab readiness'],
};

export const INITIAL_PICKUP_LOCATION = {
  address: 'Tower 4, Sector 62, Noida, Uttar Pradesh 201309',
  landmark: 'Near Stellar IT Park & Fortis Chowk',
  coordinates: {
    lat: 28.6280,
    lng: 77.3685,
  },
};

// 10 Detailed Hospitals around Noida/Delhi NCR
export const NEARBY_HOSPITALS: Hospital[] = [
  {
    id: 'HOSP-APOLLO',
    name: 'Apollo Hospital',
    coordinates: { lat: 28.5835, lng: 77.3325 }, // Sector 26 Noida
    address: 'E-2, Sector 26, Noida, Uttar Pradesh 201301',
    distanceKm: 1.8,
    etaMinutes: 6,
    emergencyAvailable: true,
    doctorsAvailable: true,
    bedsAvailable: true,
    icuAvailable: true,
    bedCount: 42,
    icuBedCount: 8,
    rating: 4.8,
    reviewCount: 3420,
    imageUrl: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=600&auto=format&fit=crop&q=80',
    specialties: ['Emergency Trauma Level 1', 'Interventional Cardiology', 'Cath Lab', 'Critical Care'],
    aiMatchScore: 96,
    aiMatchReason: 'Fastest 6-min ETA, dedicated 24/7 cardiac catheterization team on active standby.',
    phone: '+91 120 401 2000',
    status: 'AVAILABLE',
    lastUpdated: 'Updated 28s ago via Hospital API',
  },
  {
    id: 'HOSP-FORTIS',
    name: 'Fortis Hospital',
    coordinates: { lat: 28.6189, lng: 77.3732 }, // Sector 62 Noida
    address: 'B-22, Sector 62, Gautam Buddha Nagar, Noida 201301',
    distanceKm: 2.4,
    etaMinutes: 8,
    emergencyAvailable: true,
    doctorsAvailable: true,
    bedsAvailable: true,
    icuAvailable: true,
    bedCount: 58,
    icuBedCount: 14,
    rating: 4.7,
    reviewCount: 2890,
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&auto=format&fit=crop&q=80',
    specialties: ['Comprehensive Cardiac Care', 'Stroke Center', 'Trauma Emergency', 'ICU'],
    aiMatchScore: 94,
    aiMatchReason: 'Best combination of proximity, emergency availability and confirmed bed capacity.',
    phone: '+91 120 430 0222',
    status: 'AVAILABLE',
    lastUpdated: 'Verified via hospital call',
  },
  {
    id: 'HOSP-JAYPEE',
    name: 'Jaypee Hospital',
    coordinates: { lat: 28.5204, lng: 77.3789 }, // Sector 128 Noida
    address: 'Sector 128, Noida-Greater Noida Expressway, Noida 201304',
    distanceKm: 5.8,
    etaMinutes: 14,
    emergencyAvailable: true,
    doctorsAvailable: true,
    bedsAvailable: true,
    icuAvailable: true,
    bedCount: 95,
    icuBedCount: 26,
    rating: 4.6,
    reviewCount: 1950,
    imageUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600&auto=format&fit=crop&q=80',
    specialties: ['Heart Institute', 'Transplant Center', 'Emergency & Trauma', 'Neuro ICU'],
    aiMatchScore: 89,
    aiMatchReason: 'State-of-the-art super specialty center with 26 ICU beds, accessible via expressway.',
    phone: '+91 120 412 2222',
    status: 'AVAILABLE',
    lastUpdated: 'Updated 1m ago',
  },
  {
    id: 'HOSP-MAX',
    name: 'Max Super Speciality Hospital',
    coordinates: { lat: 28.6447, lng: 77.3371 }, // Vaishali
    address: 'W-3, Sector 1, Vaishali, Ghaziabad, UP 201012',
    distanceKm: 4.1,
    etaMinutes: 11,
    emergencyAvailable: true,
    doctorsAvailable: true,
    bedsAvailable: true,
    icuAvailable: false,
    bedCount: 18,
    icuBedCount: 0,
    rating: 4.5,
    reviewCount: 2210,
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=600&auto=format&fit=crop&q=80',
    specialties: ['Cardiac Sciences', 'Pulmonology', 'Emergency Critical Care'],
    aiMatchScore: 82,
    aiMatchReason: 'Excellent cardiac team, currently ICU beds are at 100% capacity.',
    phone: '+91 120 418 8000',
    status: 'LIMITED',
    lastUpdated: 'Updated 3m ago',
  },
  {
    id: 'HOSP-YATHARTH',
    name: 'Yatharth Super Speciality Hospital',
    coordinates: { lat: 28.5088, lng: 77.4042 }, // Sector 110 Noida
    address: 'Plot No. 1, Gejha Road, Sector 110, Noida 201304',
    distanceKm: 6.4,
    etaMinutes: 15,
    emergencyAvailable: true,
    doctorsAvailable: true,
    bedsAvailable: true,
    icuAvailable: true,
    bedCount: 40,
    icuBedCount: 9,
    rating: 4.4,
    reviewCount: 1450,
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&auto=format&fit=crop&q=80',
    specialties: ['Cardiology', 'Emergency Medicine', 'Critical Care ICU'],
    aiMatchScore: 80,
    aiMatchReason: 'Available emergency triage, modern ICU facility, rapid admission protocol.',
    phone: '+91 120 246 8000',
    status: 'AVAILABLE',
    lastUpdated: 'Updated 5m ago',
  },
  {
    id: 'HOSP-KAILASH',
    name: 'Kailash Hospital & Neuro Institute',
    coordinates: { lat: 28.5802, lng: 77.3401 }, // Sector 27 Noida
    address: 'H-33, Sector 27, Noida, Uttar Pradesh 201301',
    distanceKm: 3.5,
    etaMinutes: 10,
    emergencyAvailable: true,
    doctorsAvailable: true,
    bedsAvailable: true,
    icuAvailable: true,
    bedCount: 22,
    icuBedCount: 4,
    rating: 4.3,
    reviewCount: 1680,
    imageUrl: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=600&auto=format&fit=crop&q=80',
    specialties: ['Emergency Care', 'Neurotrauma', 'Cardiology', 'General Surgery'],
    aiMatchScore: 78,
    aiMatchReason: 'Central Noida location, active emergency triage, moderate bed availability.',
    phone: '+91 120 244 4444',
    status: 'AVAILABLE',
    lastUpdated: 'Updated 7m ago',
  },
  {
    id: 'HOSP-METRO',
    name: 'Metro Hospital & Heart Institute',
    coordinates: { lat: 28.5991, lng: 77.3298 }, // Sector 11 Noida
    address: 'L-94, Sector 11, Noida, Uttar Pradesh 201301',
    distanceKm: 4.8,
    etaMinutes: 13,
    emergencyAvailable: true,
    doctorsAvailable: true,
    bedsAvailable: false,
    icuAvailable: true,
    bedCount: 5,
    icuBedCount: 2,
    rating: 4.2,
    reviewCount: 920,
    imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600&auto=format&fit=crop&q=80',
    specialties: ['Dedicated Heart Institute', 'Cath Lab', 'Cardiac ICU'],
    aiMatchScore: 74,
    aiMatchReason: 'Specialized cardiac hospital, general wards nearly full.',
    phone: '+91 120 436 6666',
    status: 'LIMITED',
    lastUpdated: 'Updated 2m ago',
  },
  {
    id: 'HOSP-FELIX',
    name: 'Felix Hospital',
    coordinates: { lat: 28.5135, lng: 77.3912 }, // Sector 137 Noida
    address: 'Sector 137, Expressway, Noida, UP 201305',
    distanceKm: 7.2,
    etaMinutes: 16,
    emergencyAvailable: true,
    doctorsAvailable: true,
    bedsAvailable: true,
    icuAvailable: true,
    bedCount: 30,
    icuBedCount: 6,
    rating: 4.2,
    reviewCount: 780,
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&auto=format&fit=crop&q=80',
    specialties: ['Accident & Emergency', 'Cardiology', 'Intensive Care'],
    aiMatchScore: 71,
    aiMatchReason: 'Modern facility along expressway, good alternative if inner city roads have traffic.',
    phone: '+91 120 398 8888',
    status: 'AVAILABLE',
    lastUpdated: 'Updated 10m ago',
  },
  {
    id: 'HOSP-SHARDA',
    name: 'Sharda Hospital & Trauma Center',
    coordinates: { lat: 28.4731, lng: 77.4839 }, // Knowledge Park III
    address: 'Plot No. 32-34, Knowledge Park III, Greater Noida 201306',
    distanceKm: 14.5,
    etaMinutes: 24,
    emergencyAvailable: true,
    doctorsAvailable: true,
    bedsAvailable: true,
    icuAvailable: true,
    bedCount: 120,
    icuBedCount: 35,
    rating: 4.1,
    reviewCount: 1100,
    imageUrl: 'https://images.unsplash.com/photo-1596541223130-5d31a73fb6c6?w=600&auto=format&fit=crop&q=80',
    specialties: ['Level 1 Multi-Trauma', 'Super Specialty Medical Center', 'Mass Casualty Unit'],
    aiMatchScore: 65,
    aiMatchReason: 'Largest tertiary capacity (120 beds), but further distance (14.5 km).',
    phone: '+91 120 232 9999',
    status: 'AVAILABLE',
    lastUpdated: 'Updated 12m ago',
  },
  {
    id: 'HOSP-CLOUDNINE',
    name: 'Cloudnine Hospital',
    coordinates: { lat: 28.5721, lng: 77.3601 }, // Sector 51 Noida
    address: 'Plot No. A-2, Sector 51, Noida, Uttar Pradesh 201301',
    distanceKm: 3.9,
    etaMinutes: 12,
    emergencyAvailable: false,
    doctorsAvailable: true,
    bedsAvailable: true,
    icuAvailable: false,
    bedCount: 12,
    icuBedCount: 0,
    rating: 4.5,
    reviewCount: 1540,
    imageUrl: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?w=600&auto=format&fit=crop&q=80',
    specialties: ['Maternity Emergency', 'Pediatric ICU', 'Neonatology'],
    aiMatchScore: 48,
    aiMatchReason: 'Specialized maternity hospital - NOT recommended for acute adult cardiac emergencies.',
    phone: '+91 120 405 5555',
    status: 'UNAVAILABLE',
    lastUpdated: 'Updated 15m ago',
  },
];

export const SAMPLE_TRIP_HISTORY: TripHistoryItem[] = [
  {
    id: 'TRIP-802',
    bookingId: 'SVF-10288',
    date: 'Today, 09:15 AM',
    patientName: 'Meera Verma',
    emergencyLevel: 'CRITICAL',
    pickupAddress: 'Sector 50, Noida',
    hospitalName: 'Apollo Hospital (Sector 26)',
    distanceKm: 4.2,
    durationMinutes: 11,
    fare: 520,
    driverEarnings: 442,
    status: 'Completed',
    otpVerified: true,
    aiRerouted: false,
  },
  {
    id: 'TRIP-801',
    bookingId: 'SVF-10274',
    date: 'Today, 07:40 AM',
    patientName: 'Sunil Gupta',
    emergencyLevel: 'HIGH',
    pickupAddress: 'Sector 76, Noida',
    hospitalName: 'Fortis Hospital (Sector 62)',
    distanceKm: 6.8,
    durationMinutes: 16,
    fare: 680,
    driverEarnings: 578,
    status: 'Hospital Redirected',
    otpVerified: true,
    aiRerouted: true,
  },
  {
    id: 'TRIP-800',
    bookingId: 'SVF-10261',
    date: 'Yesterday, 11:30 PM',
    patientName: 'Ananya Roy',
    emergencyLevel: 'MEDIUM',
    pickupAddress: 'Indirapuram, Ghaziabad',
    hospitalName: 'Max Super Speciality Vaishali',
    distanceKm: 3.1,
    durationMinutes: 9,
    fare: 400,
    driverEarnings: 340,
    status: 'Completed',
    otpVerified: true,
    aiRerouted: false,
  },
  {
    id: 'TRIP-799',
    bookingId: 'SVF-10250',
    date: 'Yesterday, 08:15 PM',
    patientName: 'Vikramjit Singh',
    emergencyLevel: 'CRITICAL',
    pickupAddress: 'Sector 128, Noida Expressway',
    hospitalName: 'Jaypee Hospital',
    distanceKm: 7.5,
    durationMinutes: 14,
    fare: 750,
    driverEarnings: 637,
    status: 'Completed',
    otpVerified: true,
    aiRerouted: false,
  },
  {
    id: 'TRIP-798',
    bookingId: 'SVF-10239',
    date: 'Yesterday, 04:00 PM',
    patientName: 'Kavita Joshi',
    emergencyLevel: 'HIGH',
    pickupAddress: 'Sector 18 Market, Noida',
    hospitalName: 'Kailash Hospital Sector 27',
    distanceKm: 2.8,
    durationMinutes: 8,
    fare: 450,
    driverEarnings: 382,
    status: 'Completed',
    otpVerified: true,
    aiRerouted: false,
  },
];

export const INITIAL_EARNINGS: EarningsData = {
  todayEarnings: 2450,
  completedTrips: 8,
  onlineHours: '7h 42m',
  averageTripFare: 306,
  weeklyEarnings: [
    { day: 'Mon', amount: 2850, trips: 9 },
    { day: 'Tue', amount: 3100, trips: 10 },
    { day: 'Wed', amount: 2450, trips: 8 },
    { day: 'Thu', amount: 3400, trips: 11 },
    { day: 'Fri', amount: 3800, trips: 12 },
    { day: 'Sat', amount: 4200, trips: 13 },
    { day: 'Sun', amount: 2450, trips: 8 },
  ],
  recentPayouts: [
    { id: 'PAY-901', date: 'Sep 12, 2026', amount: 18450, status: 'PAID' },
    { id: 'PAY-900', date: 'Sep 05, 2026', amount: 16800, status: 'PAID' },
    { id: 'PAY-899', date: 'Aug 29, 2026', amount: 19200, status: 'PAID' },
  ],
  incentives: [
    {
      title: 'Peak Emergency Duty (10 PM - 6 AM)',
      reward: 500,
      progress: 6,
      total: 6,
      expires: 'Completed today',
    },
    {
      title: 'Complete 10 High-Priority Trips',
      reward: 750,
      progress: 8,
      total: 10,
      expires: '2 trips left today',
    },
    {
      title: '5-Star Emergency Rating Streak',
      reward: 1000,
      progress: 18,
      total: 20,
      expires: '2 days remaining',
    },
  ],
};
